<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grade_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get grade by studentid
     */
    function get_grade($studentid)
    {
        return $this->db->get_where('grades',array('studentid'=>$studentid))->row_array();
    }
        
    /*
     * Get all grades
     */
    function get_all_grades()
    {
        $this->db->order_by('studentid');
        return $this->db->get('grades')->result_array();
    }
        
    /*
     * function to add new grade
     */
    function add_grade($params)
    {
        $this->db->insert('grades',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update grade
     */
    function update_grade($studentid,$params)
    {
        $this->db->where('studentid',$studentid);
        return $this->db->update('grades',$params);
    }
    
    /*
     * function to delete grade
     */
    function delete_grade($studentid)
    {
        return $this->db->delete('grades',array('studentid'=>$studentid));
    }
}
